### ISSUE TITLE
nav2 instability

### ISSUE THREAD

**Issue by girvenavery2022** [iscumd/Mammoth#63]
# information 

Due to mammoths large system, things need to be brought up in order for it to correctly work, and if it doesn't, things don't work.  Thankfully nav2 has a lifecycle manager to allow us to manage the entire system from start to finish. 
Right now, nav2 manages itself and the ouster driver. This causes some instability depending on when slam toolbox is brought up or the realsense is brought up for Odom. So after comp, I should plan to add the realsense driver to the lifecycle manager as well as slam toolbox

**Comment by dcutting133** [comment]
I'm thinking the launching should be good with this, so long as the LiDAR is configured well on the robot. I'm a bit concerned about the navstack's performance, but it seems to be significantly better than the ROS1 navstack.

I think we should look in to writing our own planners as we have in previous years.

Leaving this open for discussion?

**Comment by girvenavery2022** [comment]
yeah I think we should eventually write our own planners. although galactic has so far solved the instability, I am down to writing our own.
I would definitely leave this open for discussion

**Comment by davidcutting** [comment]
Lots of stability improvements for nav2 slated for new Humble release. See Ohm repo for usage of navstack and see Andy's fix.

Additionally, effort to make our own planners going here:
https://github.com/davidcutting/isc_nav
