### ISSUE TITLE
Inablilty to launch from CLI over SSH

### ISSUE THREAD

**Issue by andyblarblar** [iscumd/Mammoth#64]
We found at competition that yeti cannot be started nor controlled over ssh. This is a major inconvienience, as the software must thus be started using a monitor we litterally put on the bot. Fixing this issue would make using Yeti in competition much easier.

EDIT:
To clarify, this is really two issues

- [x] Teleop fails when mammoth is launched from a computer over SSH, and the controller is connected to yeti
- [x] The initalpose is not published when mammoth is launched over SSH (even when manually set via command line, although this may be due to operator error)

**Comment by dcutting133** [comment]
What do you mean by cannot be started or controlled? What's failing?

Can you SSH in to the robot computer?
What happens when you roslaunch?

There should be no difference between directly using the keyboard of the laptop and using SSH.

**Comment by andyblarblar** [comment]
teleop with the xbox controller does not work over SSH, and the initalpose is not published (I belive this is because the initalpose is being set by Rviz normally)

**Comment by dcutting133** [comment]
So, if I got this right you're:
1. On your laptop connected to the robot computer with SSH.
2. The controller is plugged into your computer.
3. You're running RVIZ on your computer (to publish /initialpose?)

In order for this to work, you would need to have the controller plugged in/bluetooth to the robot computer. If you want to do it otherwise, you would need to be running the ROS node for the controller on your laptop with the proper network configuration so that the ROS nodes on the robot computer can receive the control outputs from your laptop. The same goes for RVIZ, because it would not be sending or receiving any information from the ROS master.

[Here is a guide](http://wiki.ros.org/ROS/NetworkSetup) from the ROS wiki which explains the networking setup fairly well.

**Comment by andyblarblar** [comment]
What we ran into in competition is our ROS machines dieing. This ment we were SSHing into the bot using a Windows machine and iPhone 11. We did connect to the machine with the 360 controller, but still couldnt teleop. We also had issues setting the initalpose (as Yeti currently assumes Rviz is providing it). I'm not 100% on what the issue was caused by, so this is more something we need to work on (a user story, if you will). 

FWIW in comp we ended up just disabling the entire nav stack, and teleop still didnt work unless we had launched ros using the nuc itself.

**Comment by girvenavery2022** [comment]
I don't think not being able to teleop over SSH is an issue with the ros2 code so to speak. Teleop works flawlessly without SSH so its more so an issue with trying to correctly setup SSH. For the initialpose issue, I am currently developing a new node that will allow the user to hit the start button and it will dead reckon the robot from there.

**Comment by dcutting133** [comment]
Not entirely sure how teleop would fail/not fail if being launched over SSH. SSH should be a non-factor here imo.

I suggest we just wipe the Yeti laptop, put on Ubuntu 20.04 with Galactic/Foxy and give it a run. My gut tells me it won't have any of the issues you were seeing at competition.

**Comment by andyblarblar** [comment]
> I don't think not being able to teleop over SSH is an issue with the ros2 code so to speak. Teleop works flawlessly without SSH so its more so an issue with trying to correctly setup SSH. For the initialpose issue, I am currently developing a new node that will allow the user to hit the start button and it will dead reckon the robot from there.

Great to hear you've got a solution for the initalpose. I'll mess with the SSH teleop some more now that we're back, but it was very consistent in comp. FYI David, we use an Intel Nuc now, so that's why I'm conserned about SSH so much. While it may not be a bug, this would be a huge QoL improvement in comp.

**Comment by andyblarblar** [comment]
welp, I just tested in the lab and it works fine now. Thats comp I guess ¯\_(ツ)_/¯

Closing as Avery is already working on the initalpose fix.
