### ISSUE TITLE
Potential inconsistency with Gazebo world and launch file topic remapping

### ISSUE THREAD

**Issue by JordanKra** [iscumd/Mammoth#72]
In the mammoth_gazebo gazebo launch file were hard coding the path for gazebo's clock remapping based on the name of the world as defined in the sdf file:

'/world/test/clock@rosgraph_msgs/msg/Clock[ignition.msgs.Clock'

and 

 ('/world/test/clock', '/clock'),

If the world name is changed by, for example, switching the world files to something with differing header info then the clock wont be set properly and you'll get a bunch of weird issues such as joint states not publishing and point cloud points persisting in rviz. This should probably be set to something like "mammoth_world" and all worlds created should use that name in their header information.

**Comment by dcutting133** [comment]
So, we did switch the worlds from test to single-i before marking it as completely ported. I looked into it, and the single-i.sdf world has its world name set to test, I'm assuming for the reason you described. It does work, but it probably isn't ideal.

I say we should leave this issue up as a reminder to clean this part up, or as information for people who have this issue.

**Comment by davidcutting** [comment]
Closing since this was changed to use the single-i world. This is just how Gazebo is launched. People who are interested will likely find this issue even if its closed.
